baseURL = '/'
languageCode = 'en-us'
title = 'May'

buildFuture = true
buildDrafts = false
pagination.pagerSize = 12

DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'

refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'

timeout = 60000

rssLimit = 3

enableInlineShortcodes = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4

[permalinks]
  posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
  author = 'May Freigang'
# this is the original low tech newsletter #  newsletter = 'https://d69baa34.sibforms.com/serve/MUIEAJWIw9w82Dl4ua6FQArPaI-3Qb-zVTwPNabHQgFH51MiGF69Smy9LOC_HPoUmBj0emaXsXT87gcQXDPvtu-AZsJCHWhkkv21CdrcQu4GdnYAhZ-MrIPhwGDecagLzYxqfvkaqXg2ODcbJU4ByoDmzJK3ZTczDo2jcWtfn-En0MGKLVkgxx9TgdHqYoPabMJCMF-agLEclEwv'
  description = "this is may's blog and it uses minimal energy!"

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 1
  [[menu.main]]
    identifier = 'garden'
    name = 'Garden'
    url = '/garden/'
    weight = 2
  [[menu.main]]
    identifier = 'recipes'
    name = 'Recipes'
    url = '/recipes/'
    weight = 3
 # [[menu.main]]
  #  identifier = 'obsoletetitle'
  #  name = 'Obsolete Technology'
  #  url = '/obsolete-technology/'
  #  weight = 4
 # [[menu.main]]
 #   identifier = 'offline'
  #  name = 'Offline Reading'
  #  url = '/offline-reading/'
  #  weight = 5
  [[menu.main]]
    identifier = 'archives'
    name = 'Archive'
    url = '/archives/'
    weight = 6
#  [[menu.main]]
 #   identifier = 'donate'
 #   name = 'Donate'
  #  url = '/donate/'
  #  weight = 7
 # [[menu.main]]
 #   identifier = 'ntm'
 #   name = 'NTM'
  #  url = 'https://www.notechmagazine.com/'
  #  weight = 8

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1


[taxonomies]
  author = 'authors'
  tag = 'tags'
  category = 'categories'
  translator = 'translators'
  lang = 'languages'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'lang'
    weight = 80
